name: ci-app
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - run: make setup
       - run: make test 
       - run: make lint 
